//! The About & licenses screen: the build version, punktfunk's own licence, and the
//! generated third-party notices, as one scrollable wall of text.
//!
//! Every other punktfunk client shows the version here rather than in its navigation
//! chrome, which is why the sidebar no longer draws it (see `sidebar::draw_sidebar`).
//!
//! **Scrolling is by source line, and only the visible window is ever rasterized.**
//! `THIRD-PARTY-NOTICES.txt` is ~10,000 lines; laying it out in full — or drawing it
//! through [`TextCache`] — would be a non-starter on this `SoC` (see
//! `draw_text_uncached`'s docs for the cache side of that). `draw_about_body` walks
//! forward from the first visible line and stops as soon as it runs past the bottom
//! of the viewport, so cost per frame is bounded by the viewport height, not by the
//! document length.
use anyhow::Result;
use sdl2::rect::Rect;

use super::*;

/// The packaged version (e.g. `0.4.0+git.abc12345`), threaded in at compile time via
/// `PKG_VERSION` by the Taskfile's build step. `Cargo.toml` deliberately stays a fixed
/// `0.0.1` (see CLAUDE.md), so a bare native `cargo build` falls back to
/// `CARGO_PKG_VERSION` rather than showing an empty marker.
pub const VERSION: &str = match option_env!("PKG_VERSION") {
    Some(v) => v,
    None => env!("CARGO_PKG_VERSION"),
};

/// punktfunk-webos' own licence, both halves of the `MIT OR Apache-2.0` dual grant.
const APP_LICENSE: &str = concat!(
    include_str!("../../LICENSE-MIT"),
    "\n\n=============================== Apache-2.0 ===============================\n\n",
    include_str!("../../LICENSE-APACHE"),
);

/// Third-party notices for every crate that links on the webOS target, plus the
/// bundled non-Rust components. Generated by `scripts/gen-third-party-notices.py`
/// (`task notices`) — regenerate whenever the dependency tree changes.
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

/// The whole document, as one static line list. `include_str!` gives a `&'static str`,
/// so splitting it costs one `Vec` of string slices — no copying of the ~560 KB body.
pub fn about_lines() -> Vec<&'static str> {
    let mut out = vec![
        "punktfunk for webOS",
        "",
        "A native LG webOS TV client for punktfunk — low-latency desktop and",
        "game streaming. Built on the upstream punktfunk project; all credit for",
        "the protocol, FEC/crypto core, and host implementation belongs there.",
        "",
        "  https://github.com/dyptan-io/pf-webos",
        "  https://git.unom.io/unom/punktfunk",
        "",
        "Licensed under MIT OR Apache-2.0, at your option.",
        "",
        "========================================================================",
        "PUNKTFUNK-WEBOS LICENCE",
        "========================================================================",
        "",
    ];
    out.extend(APP_LICENSE.lines());
    out.push("");
    out.extend(THIRD_PARTY_NOTICES.lines());
    out
}

pub const ABOUT_WIDTH_FRAC: f32 = 0.78;
/// Fraction of the panel height the card occupies — tall, since this is a reading page.
const ABOUT_HEIGHT_FRAC: f32 = 0.84;
const SIDE_PAD: i32 = 40;
/// Vertical gap between rendered lines, on top of the font's own height.
const LINE_GAP: i32 = 4;

pub fn about_card_rect(screen_w: u32, screen_h: u32) -> Rect {
    let height = (screen_h as f32 * ABOUT_HEIGHT_FRAC).round() as u32;
    modal_card_rect(screen_w, screen_h, ABOUT_WIDTH_FRAC, height)
}

/// The scrolling viewport inside `card`, below the header.
pub fn about_body_rect(card: Rect, fonts: &Fonts) -> Rect {
    let header_end = modal_header_end_y(fonts.label, fonts.value, card, ABOUT_SUBTITLE_PROBE);
    let top = header_end + 20;
    let bottom = card.y() + card.height() as i32 - 28;
    Rect::new(
        card.x() + SIDE_PAD,
        top,
        card.width().saturating_sub(SIDE_PAD as u32 * 2),
        (bottom - top).max(0) as u32,
    )
}

/// A fixed-length stand-in for the real subtitle when measuring the header's height.
/// The subtitle is `Version <VERSION>` — one line at every realistic version string —
/// so the body rect stays put regardless of what the build stamped in.
const ABOUT_SUBTITLE_PROBE: &str = "Version 0.0.0+git.00000000";

/// How many source lines fit in `body` at worst (every line unwrapped) — used to
/// clamp scrolling so the page can't be scrolled past its own end.
pub fn about_visible_lines(body: Rect, font: &sdl2::ttf::Font) -> usize {
    let step = (font.height() + LINE_GAP).max(1);
    (body.height() as i32 / step).max(1) as usize
}

/// Draws the document from source line `first` until the viewport is full, wrapping
/// each line to the viewport width. Only the lines actually shown are rasterized —
/// see the module docs.
pub fn draw_about_body(
    painter: &mut Painter,
    font: &sdl2::ttf::Font,
    lines: &[&str],
    first: usize,
    body: Rect,
) -> Result<()> {
    let step = font.height() + LINE_GAP;
    let mut y = body.y();
    let bottom = body.y() + body.height() as i32;
    for line in lines.iter().skip(first) {
        if y + font.height() > bottom {
            break;
        }
        if line.trim().is_empty() {
            y += step;
            continue;
        }
        // Wrapped, not clipped: this is licence text, and silently truncating it at the
        // card edge would hide terms the screen exists to display.
        for part in wrap_text(font, line, body.width()) {
            if y + font.height() > bottom {
                break;
            }
            draw_text_uncached(painter, font, &part, body.x(), y, MUTED)?;
            y += step;
        }
    }
    Ok(())
}
